language: python
python:
  - "3.6"
install:
  - sudo apt update
  - pip install -e .
script:
  - pytest --cov-report=xml --cov=torch_nf tests -W ignore::DeprecationWarning
env:
  - CODECOV_TOKEN="b22892d3-c31d-4841-b2f3-34eb120f54dd"
after_success:
  - bash <(curl -s https://codecov.io/bash)
